- https://github.com/swcarpentry/2013-08-23-harvard
- https://github.com/swcarpentry/2013-09-16-stsci
- https://github.com/jdblischak/2013-09-19-chicago
- https://github.com/arokem/2013-09-16-ISI
- https://github.com/jdblischak/2013-10-03-pasteur
- https://github.com/swcarpentry/2013-10-09-canberra
- https://github.com/jdblischak/2013-10-17-uic
- https://github.com/swcarpentry/2013-10-24-greenwich
- https://github.com/justincely/2013-10-25-columbia
- https://github.com/chryswoods/2013-11-14-exeter
- https://github.com/damienirving/2013-11-25-unimelb
- https://github.com/mikej888/2013-12-03-edinburgh
- https://github.com/wltrimbl/2013-12-03-sesync
- https://github.com/bendmorris/2013-12-12-glasgow
- https://github.com/gvwilson/2013-12-16-dundee
- https://github.com/jooolia/2014-01-06-unb
- https://github.com/sje30/2014-01-07-cam
- https://github.com/adina/2014-01-08-iastate
- https://github.com/gvwilson/2014-01-13-toronto
- https://github.com/iglpdc/2014-01-13-uri
- https://github.com/uw-madison-aci/2014-01-13-wisc
- https://github.com/apawlik/2014-01-14-manchester
- https://github.com/swcarpentry/2014-01-18-ucb
- https://github.com/gvwilson/2014-01-20-montreal
- https://github.com/geocarpentry/2014-01-21-erdc
- https://github.com/arokem/2014-01-27-Stanford
- https://github.com/jennybc/2014-01-27-miami
- https://github.com/uiuc-cse/2014-01-30-cse
- https://github.com/geocarpentry/2014-01-30-mit
- https://github.com/swcarpentry/2014-01-31-ucsb
- https://github.com/apawlik/2014-02-03-TGAC
- https://github.com/damienirving/2014-02-10-hobart
- https://github.com/swcarpentry/2014-02-11-toronto
- https://github.com/bernhardkonrad/2014-02-22-SFU
- https://github.com/swcarpentry/2014-02-15-umkc
- https://github.com/nicercode/2014-02-13-UNSW
- https://github.com/nicercode/2014-02-18-UTS
- https://github.com/justincely/2014-02-24-esac
- https://github.com/swcarpentry/2014-03-17-nyu
- https://github.com/swcarpentry/2014-03-17-ucb
- https://github.com/swcarpentry/2014-03-17-uw
- https://github.com/swcarpentry/2014-04-14-wise
- https://github.com/swcarpentry/2014-04-14-pycon
- https://github.com/swcarpentry/2014-04-14-pycon-ngs
- https://github.com/swcarpentry/2014-04-14-pycon-r
